//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kelasi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Topic_TopicId { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
