//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kelasi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Categories = new HashSet<Category>();
            this.Videos = new HashSet<Video>();
        }
    
        public int TopicId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Library_LibraryId { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
