//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kelasi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Authors
    {
        public Users_Authors()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int AuthorId { get; set; }
        public string Bio { get; set; }
        public string Title { get; set; }
        public Nullable<int> User_UserId { get; set; }
    
        public virtual ICollection<Video> Videos { get; set; }
    }
}
