//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kelasi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime ReleasedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Duration { get; set; }
        public int NumberOfviewers { get; set; }
        public int NumberOfSubscribers { get; set; }
        public int Size { get; set; }
        public string Url { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Category_CategoryId { get; set; }
        public Nullable<int> Topic_TopicId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> Language_LanguageId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual Users_Authors Users_Authors { get; set; }
    }
}
